"""add workflow graph json field

Revision ID: 20230914_164435
Revises: 20230914_095959
Create Date: 2023-09-14 23:42:24.854214

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '20230914_164435'
down_revision = '20230914_095959'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('producing_run_id', sa.Integer(), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity'))
    )
    op.add_column('workflow_version', sa.Column('graph_json', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_version', 'graph_json')
    op.drop_table('entity')
    # ### end Alembic commands ###
