"""add legacy_ids to driver tables to identify equivalent records across legacy and nextgen data stores

Revision ID: 20240223_112128
Revises: 20240204_202551
Create Date: 2024-02-23 16:21:29.218807

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '20240223_112128'
down_revision = '20240204_202551'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_run', sa.Column('rails_workflow_run_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_run', 'rails_workflow_run_id')
    # ### end Alembic commands ###
