"""

Revision ID: 20240130_195510
Revises: 20240128_222905
Create Date: 2024-01-31 03:55:11.432738

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "20240130_195510"
down_revision = "20240128_222905"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "entity", sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)
    )
    op.add_column("entity", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("entity", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("entity", "deleted_at")
    op.drop_column("entity", "updated_at")
    op.drop_column("entity", "created_at")
    # ### end Alembic commands ###
