"""

Revision ID: 20240305_142809
Revises: 20240228_120215
Create Date: 2024-03-05 22:28:11.148676

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "20240305_142809"
down_revision = "20240228_120215"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workflow_run", sa.Column("error_message", sa.String(), nullable=True))
    op.add_column("workflow_version", sa.Column("deprecated", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workflow_version", "deprecated")
    op.drop_column("workflow_run", "error_message")
    # ### end Alembic commands ###
