version: "3.8"

services:
  # Mock boto with persistence.
  # To use it from the CLI: aws --endpoint-url=http://localhost:4000 s3 ls
  # To reset all services without restarting the container: curl -X POST http://localhost:4000/moto-api/reset
  motoserver:
    image: motoserver/moto:4.2.3
    ports:
      - "4000:4000"
    environment:
      - MOTO_PORT=4000
      - MOTO_ENABLE_RECORDING=True
      - S3_IGNORE_SUBDOMAIN_BUCKETNAME=True
      - MOTO_S3_CUSTOM_ENDPOINTS=http://motoserver.czidnet:4000
    volumes:
      - .moto_recording:/moto/moto_recording
      - ./bin:/moto/bin
    entrypoint: []
    command: ["/moto/bin/init_moto.sh"]

networks:
  default:
    name: czidnet
    driver: overlay
    attachable: true
