version: "3.8"

services:
  # Mock boto with persistence.
  # To use it from the CLI: aws --endpoint-url=http://localhost:4000 s3 ls
  # To reset all services without restarting the container: curl -X POST http://localhost:4000/moto-api/reset
  motoserver:
    image: motoserver/moto:latest
    ports:
      - "4000:4000"
    environment:
      - MOTO_PORT=4000 # set moto listener port with env var

networks:
  default:
    name: czidnet
    driver: overlay
    attachable: true
