"""add file timestamps

Create Date: 2024-01-31 21:58:55.818246

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '20240131_135854'
down_revision = '20240129_115001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('file', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('file', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'deleted_at')
    op.drop_column('file', 'updated_at')
    op.drop_column('file', 'created_at')
    # ### end Alembic commands ###
