"""simplify schema 3

Create Date: 2024-01-29 19:02:53.744724

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '20240129_110253'
down_revision = '20240125_161939'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consensus_genome', sa.Column('metrics_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_consensus_genome_metrics_id_metric_consensus_genome'), 'consensus_genome', 'metric_consensus_genome', ['metrics_id'], ['entity_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_consensus_genome_metrics_id_metric_consensus_genome'), 'consensus_genome', type_='foreignkey')
    op.drop_column('consensus_genome', 'metrics_id')
    # ### end Alembic commands ###
