"""rename artic_v3 to artic_short_amplicons

Create Date: 2024-04-11 22:46:07.513884

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "20240411_154606"
down_revision = "20240403_111850"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sequencing_read",
        "protocol",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum(
            "ampliseq",
            "artic",
            "artic_short_amplicons",
            "artic_v4",
            "artic_v5",
            "combined_msspe_artic",
            "covidseq",
            "midnight",
            "msspe",
            "snap",
            "varskip",
            "easyseq",
            name="sequencingprotocol",
            native_enum=False,
        ),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sequencing_read",
        "protocol",
        existing_type=sa.Enum(
            "ampliseq",
            "artic",
            "artic_v3",
            "artic_v4",
            "artic_v5",
            "combined_msspe_artic",
            "covidseq",
            "midnight",
            "msspe",
            "snap",
            "varskip",
            "easyseq",
            name="sequencingprotocol",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
