"""add czid index generation

Create Date: 2024-01-05 21:37:09.191551

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "20240105_133708"
down_revision = "20231221_135013"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sequence_alignment_index", sa.Column("version", sa.String(), nullable=True))
    op.alter_column("sequence_alignment_index", "reference_genome_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column(
        "sequence_alignment_index",
        "tool",
        existing_type=sa.VARCHAR(length=8),
        type_=sa.Enum("bowtie2", "minimap2", "czid_index_generation", name="alignmenttool", native_enum=False),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sequence_alignment_index",
        "tool",
        existing_type=sa.Enum("bowtie2", "minimap2", "czid_index_generation", name="alignmenttool", native_enum=False),
        type_=sa.VARCHAR(length=8),
        existing_nullable=False,
    )
    op.alter_column("sequence_alignment_index", "reference_genome_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("sequence_alignment_index", "version")
    # ### end Alembic commands ###
