"""simplify schema part 2

Create Date: 2024-01-25 19:45:24.652925

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '20240125_114523'
down_revision = '20240125_110051'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric_consensus_genome', sa.Column('coverage_viz_summary_file_id', sa.UUID(), nullable=True))
    op.drop_constraint('fk_metric_consensus_genome_coverage_viz_id_file', 'metric_consensus_genome', type_='foreignkey')
    op.create_foreign_key(op.f('fk_metric_consensus_genome_coverage_viz_summary_file_id_file'), 'metric_consensus_genome', 'file', ['coverage_viz_summary_file_id'], ['id'])
    op.drop_column('metric_consensus_genome', 'coverage_breadth')
    op.drop_column('metric_consensus_genome', 'coverage_viz_id')
    op.drop_column('metric_consensus_genome', 'coverage_total_length')
    op.drop_column('metric_consensus_genome', 'coverage_bin_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric_consensus_genome', sa.Column('coverage_bin_size', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('metric_consensus_genome', sa.Column('coverage_total_length', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('metric_consensus_genome', sa.Column('coverage_viz_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('metric_consensus_genome', sa.Column('coverage_breadth', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_metric_consensus_genome_coverage_viz_summary_file_id_file'), 'metric_consensus_genome', type_='foreignkey')
    op.create_foreign_key('fk_metric_consensus_genome_coverage_viz_id_file', 'metric_consensus_genome', 'file', ['coverage_viz_id'], ['id'])
    op.drop_column('metric_consensus_genome', 'coverage_viz_summary_file_id')
    # ### end Alembic commands ###
