"""add legacy_ids to driver tables to identify equivalent records across legacy and nextgen data stores

Create Date: 2024-02-23 16:15:54.020050

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '20240223_111553'
down_revision = '20240209_112845'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('host_organism', sa.Column('rails_host_genome_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_taxon_tax_subspecies_id_taxon', 'taxon', type_='foreignkey')
    op.drop_column('taxon', 'tax_subspecies_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taxon', sa.Column('tax_subspecies_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_taxon_tax_subspecies_id_taxon', 'taxon', 'taxon', ['tax_subspecies_id'], ['entity_id'])
    op.drop_column('host_organism', 'rails_host_genome_id')
    # ### end Alembic commands ###
