"""
Pydantic validator for Contig

Auto-generated by running 'make codegen'. Do not edit.
Make changes to the template codegen/templates/api/types/class_name.py.j2 instead.
"""

# ruff: noqa: E501 Line too long


import uuid

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import Annotated


class ContigCreateInputValidator(BaseModel):
    # Pydantic stuff
    model_config = ConfigDict(from_attributes=True)

    collection_id: Annotated[int, Field()]
    sequencing_read_id: Annotated[uuid.UUID | None, Field()]
    sequence: Annotated[str, Field()]


class ContigUpdateInputValidator(BaseModel):
    # Pydantic stuff
    model_config = ConfigDict(from_attributes=True)

    collection_id: Annotated[int | None, Field()]
    sequencing_read_id: Annotated[uuid.UUID | None, Field()]
    sequence: Annotated[str | None, Field()]
