"""
Pydantic validator for HostOrganism

Auto-generated by running 'make codegen'. Do not edit.
Make changes to the template codegen/templates/api/types/class_name.py.j2 instead.
"""

# ruff: noqa: E501 Line too long


from support.enums import HostOrganismCategory

import uuid

from pydantic import BaseModel, ConfigDict, Field, StringConstraints
from typing_extensions import Annotated


class HostOrganismCreateInputValidator(BaseModel):
    # Pydantic stuff
    model_config = ConfigDict(from_attributes=True)
    rails_host_genome_id: Annotated[int | None, Field()]
    name: Annotated[
        str,
        StringConstraints(
            strip_whitespace=True,
        ),
    ]
    version: Annotated[
        str,
        StringConstraints(
            strip_whitespace=True,
        ),
    ]
    category: Annotated[HostOrganismCategory, Field()]
    is_deuterostome: Annotated[bool, Field()]
    producing_run_id: Annotated[uuid.UUID | None, Field()]
    collection_id: Annotated[
        int,
        Field(
            ge=0,
        ),
    ]


class HostOrganismUpdateInputValidator(BaseModel):
    # Pydantic stuff
    model_config = ConfigDict(from_attributes=True)
    name: Annotated[
        str | None,
        StringConstraints(
            strip_whitespace=True,
        ),
    ]
    version: Annotated[
        str | None,
        StringConstraints(
            strip_whitespace=True,
        ),
    ]
    category: Annotated[HostOrganismCategory | None, Field()]
    is_deuterostome: Annotated[bool | None, Field()]
