"""
Pydantic validator for ReferenceGenome

Auto-generated by running 'make codegen'. Do not edit.
Make changes to the template codegen/templates/api/types/class_name.py.j2 instead.
"""

# ruff: noqa: E501 Line too long


import uuid

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import Annotated


class ReferenceGenomeCreateInputValidator(BaseModel):
    # Pydantic stuff
    model_config = ConfigDict(from_attributes=True)

    collection_id: Annotated[int, Field()]
    file_id: Annotated[uuid.UUID | None, Field()]
    file_index_id: Annotated[uuid.UUID | None, Field()]
    name: Annotated[str, Field()]
    description: Annotated[str, Field()]
    taxon_id: Annotated[uuid.UUID, Field()]
    accession_id: Annotated[str | None, Field()]


class ReferenceGenomeUpdateInputValidator(BaseModel):
    # Pydantic stuff
    model_config = ConfigDict(from_attributes=True)

    collection_id: Annotated[int | None, Field()]
    file_id: Annotated[uuid.UUID | None, Field()]
    file_index_id: Annotated[uuid.UUID | None, Field()]
    name: Annotated[str | None, Field()]
    description: Annotated[str | None, Field()]
    taxon_id: Annotated[uuid.UUID | None, Field()]
    accession_id: Annotated[str | None, Field()]
