"""
Pydantic validator for Sample

Auto-generated by running 'make codegen'. Do not edit.
Make changes to the template codegen/templates/api/types/class_name.py.j2 instead.
"""

# ruff: noqa: E501 Line too long


import datetime
import uuid

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import Annotated


class SampleCreateInputValidator(BaseModel):
    # Pydantic stuff
    model_config = ConfigDict(from_attributes=True)

    collection_id: Annotated[int, Field()]
    name: Annotated[str, Field()]
    sample_type: Annotated[str, Field()]
    water_control: Annotated[bool, Field()]
    collection_date: Annotated[datetime.datetime | None, Field()]
    collection_location: Annotated[str, Field()]
    description: Annotated[str | None, Field()]
    host_taxon_id: Annotated[uuid.UUID | None, Field()]


class SampleUpdateInputValidator(BaseModel):
    # Pydantic stuff
    model_config = ConfigDict(from_attributes=True)

    collection_id: Annotated[int | None, Field()]
    name: Annotated[str | None, Field()]
    sample_type: Annotated[str | None, Field()]
    water_control: Annotated[bool | None, Field()]
    collection_date: Annotated[datetime.datetime | None, Field()]
    collection_location: Annotated[str | None, Field()]
    description: Annotated[str | None, Field()]
    host_taxon_id: Annotated[uuid.UUID | None, Field()]
