"""
Pydantic validator for SequencingRead

Auto-generated by running 'make codegen'. Do not edit.
Make changes to the template codegen/templates/api/types/class_name.py.j2 instead.
"""

# ruff: noqa: E501 Line too long


import uuid

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import Annotated


class SequencingReadCreateInputValidator(BaseModel):
    # Pydantic stuff
    model_config = ConfigDict(from_attributes=True)

    collection_id: Annotated[int, Field()]
    sample_id: Annotated[uuid.UUID | None, Field()]
    # TODO what do we do about enums here. GraphQL is supposed to take care of that for us I think?
    #    protocol: Annotated[ SequencingProtocol, Field()]
    r1_file_id: Annotated[uuid.UUID | None, Field()]
    r2_file_id: Annotated[uuid.UUID | None, Field()]
    # TODO what do we do about enums here. GraphQL is supposed to take care of that for us I think?
    #    technology: Annotated[ SequencingTechnology, Field()]
    # TODO what do we do about enums here. GraphQL is supposed to take care of that for us I think?
    #    nucleic_acid: Annotated[ NucleicAcid, Field()]
    has_ercc: Annotated[bool, Field()]
    taxon_id: Annotated[uuid.UUID | None, Field()]
    primer_file_id: Annotated[uuid.UUID | None, Field()]


class SequencingReadUpdateInputValidator(BaseModel):
    # Pydantic stuff
    model_config = ConfigDict(from_attributes=True)

    collection_id: Annotated[int | None, Field()]
    sample_id: Annotated[uuid.UUID | None, Field()]
    # TODO what do we do about enums here. GraphQL is supposed to take care of that for us I think?
    #    protocol: Annotated[ SequencingProtocol | None, Field()]
    r1_file_id: Annotated[uuid.UUID | None, Field()]
    r2_file_id: Annotated[uuid.UUID | None, Field()]
    # TODO what do we do about enums here. GraphQL is supposed to take care of that for us I think?
    #    technology: Annotated[ SequencingTechnology | None, Field()]
    # TODO what do we do about enums here. GraphQL is supposed to take care of that for us I think?
    #    nucleic_acid: Annotated[ NucleicAcid | None, Field()]
    has_ercc: Annotated[bool | None, Field()]
    taxon_id: Annotated[uuid.UUID | None, Field()]
    primer_file_id: Annotated[uuid.UUID | None, Field()]
