"""
Pydantic validator for Taxon

Auto-generated by running 'make codegen'. Do not edit.
Make changes to the template codegen/templates/api/types/class_name.py.j2 instead.
"""

# ruff: noqa: E501 Line too long


import uuid

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import Annotated


class TaxonCreateInputValidator(BaseModel):
    # Pydantic stuff
    model_config = ConfigDict(from_attributes=True)
    wikipedia_id: Annotated[str | None, Field()]
    description: Annotated[str | None, Field()]
    common_name: Annotated[str | None, Field()]
    name: Annotated[str | None, Field()]
    is_phage: Annotated[bool | None, Field()]
    upstream_database_id: Annotated[uuid.UUID | None, Field()]
    upstream_database_identifier: Annotated[str | None, Field()]
    # TODO what do we do about enums here. GraphQL is supposed to take care of that for us I think?
    #    level: Annotated[ TaxonLevel | None, Field()]
    tax_parent_id: Annotated[uuid.UUID | None, Field()]
    tax_subspecies_id: Annotated[uuid.UUID | None, Field()]
    tax_species_id: Annotated[uuid.UUID | None, Field()]
    tax_genus_id: Annotated[uuid.UUID | None, Field()]
    tax_family_id: Annotated[uuid.UUID | None, Field()]
    tax_order_id: Annotated[uuid.UUID | None, Field()]
    tax_class_id: Annotated[uuid.UUID | None, Field()]
    tax_phylum_id: Annotated[uuid.UUID | None, Field()]
    tax_kingdom_id: Annotated[uuid.UUID | None, Field()]
    tax_superkingdom_id: Annotated[uuid.UUID | None, Field()]
    producing_run_id: Annotated[uuid.UUID | None, Field()]
    collection_id: Annotated[int | None, Field()]


class TaxonUpdateInputValidator(BaseModel):
    # Pydantic stuff
    model_config = ConfigDict(from_attributes=True)
    wikipedia_id: Annotated[str | None, Field()]
    description: Annotated[str | None, Field()]
    common_name: Annotated[str | None, Field()]
    is_phage: Annotated[bool | None, Field()]
    # TODO what do we do about enums here. GraphQL is supposed to take care of that for us I think?
    #    level: Annotated[ TaxonLevel | None, Field()]
    tax_parent_id: Annotated[uuid.UUID | None, Field()]
    tax_subspecies_id: Annotated[uuid.UUID | None, Field()]
    tax_species_id: Annotated[uuid.UUID | None, Field()]
    tax_genus_id: Annotated[uuid.UUID | None, Field()]
    tax_family_id: Annotated[uuid.UUID | None, Field()]
    tax_order_id: Annotated[uuid.UUID | None, Field()]
    tax_class_id: Annotated[uuid.UUID | None, Field()]
    tax_phylum_id: Annotated[uuid.UUID | None, Field()]
    tax_kingdom_id: Annotated[uuid.UUID | None, Field()]
    tax_superkingdom_id: Annotated[uuid.UUID | None, Field()]
