version: "3.8"

services:
  entities-db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password_postgres
      - POSTGRES_DB=entities
      # The postgres image declares a mounted volume at /var/lib/postgresql/data
      # by default, which means that the data in that directory is difficult to
      # snapshot and export. Here, we're telling Postgres to use this (non-mounted)
      # directory as its storage location instead so it works with our db snapshot
      # workflow.
      - PGDATA=/var/lib/platformics/data
  cerbos:
    image: ghcr.io/cerbos/cerbos:0.29.0
    ports:
      - "3592:3592"
      - "3593:3593"
    volumes:
      - ./cerbos:/entities
    command:
      ["server", "--config", "/entities/config/config.yaml"]
  entities:
    image: "platformics-entities"
    build:
      context: ".."
      dockerfile: "entities/Dockerfile"
      args:
        - BUILDKIT_INLINE_CACHE=1
    restart: always
    stdin_open: true # Helps with pdb
    tty: true # Helps with pdb
    ports:
      - "8008:8008"
    environment:
      - CERBOS_URL=http://cerbos:3592
      - DB_HOST=entities-db.czidnet
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=password_postgres
      - DB_NAME=entities
      - DEFAULT_UPLOAD_BUCKET=local-bucket
      - BOTO_ENDPOINT_URL=http://motoserver.czidnet:4000
      - AWS_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      # TODO - these are keypairs for testing only! Do not use in prod!!
      - JWK_PUBLIC_KEY_FILE=/czid-platformics/entities/test_infra/fixtures/public_key.pem
      - JWK_PRIVATE_KEY_FILE=/czid-platformics/entities/test_infra/fixtures/private_key.pem
    volumes:
      - ./:/czid-platformics/entities
      - ../platformics:/czid-platformics/entities/platformics
networks:
  default:
    name: czidnet
    driver: overlay
    attachable: true
    external: true
