# Auto-generated by 'happy infra'. Do not edit
# Make improvements in happy, so that everyone can benefit.
module "stack" {
  source           = "git@github.com:chanzuckerberg/happy//terraform/modules/happy-stack-eks?ref=main"
  image_tag        = var.image_tag
  stack_name       = var.stack_name
  k8s_namespace    = var.k8s_namespace
  image_tags       = jsondecode(var.image_tags)
  stack_prefix     = "/${var.stack_name}"
  app_name         = var.app
  deployment_stage = "dev"
  additional_env_vars = {
    CERBOS_URL="http://cerbos:3592"
    JWK_PUBLIC_KEY_FILE="/czid-platformics/entities/test_infra/fixtures/public_key.pem"
    JWK_PRIVATE_KEY_FILE="/czid-platformics/entities/test_infra/fixtures/private_key.pem"
    DEFAULT_UPLOAD_BUCKET="local-bucket"
    BOTO_ENDPOINT_URL="http://motoserver.czidnet:4000"
    AWS_REGION="us-west-2"
  }
  services = {
    entities = {
      health_check_path     = "/graphql"
      cpu                   = "2" # TODO: right size this as necessary
      memory                = "1000Mi" # TODO: right size this as necessary
      name                  = "entities"
      platform_architecture = "arm64"
      port                  = 8008
      service_type          = "INTERNAL"
    }
  }
  create_dashboard = false
  routing_method   = "CONTEXT"

  tasks = {
    # TODO: Fix migrate task to run properly post-deployment
    migrate = {
      image  = "{entities}:${var.image_tag}"
      memory = "1000Mi"
      cpu    = "100m"
      cmd    = ["/czid-platformics/entities/scripts/migrate.sh"]
    }
  }
}
