"""
GraphQL mutations for files and entities

Auto-generated by running 'make codegen'. Do not edit.
Make changes to the template codegen/templates/api/mutations.py.j2 instead.
"""

import strawberry
from typing import Sequence
from api.files import File, create_file, upload_file, mark_upload_complete, MultipartUploadResponse
from api.types.run import Run, create_run, update_run, delete_run
from api.types.workflow import Workflow, create_workflow, update_workflow, delete_workflow
from api.types.run_step import RunStep, create_run_step, update_run_step, delete_run_step
from api.types.run_entity_input import (
    RunEntityInput,
    create_run_entity_input,
    update_run_entity_input,
    delete_run_entity_input,
)
from api.types.workflow_version import (
    WorkflowVersion,
    create_workflow_version,
    update_workflow_version,
    delete_workflow_version,
)


@strawberry.type
class Mutation:
    # File mutations
    #create_file: File = create_file
    #upload_file: MultipartUploadResponse = upload_file
    #mark_upload_complete: File = mark_upload_complete

    # Run mutations
    create_run: Run = create_run
    update_run: Sequence[Run] = update_run
    delete_run: Sequence[Run] = delete_run

    # Workflow mutations
    create_workflow: Workflow = create_workflow
    update_workflow: Sequence[Workflow] = update_workflow
    delete_workflow: Sequence[Workflow] = delete_workflow

    # RunStep mutations
    create_run_step: RunStep = create_run_step
    update_run_step: Sequence[RunStep] = update_run_step
    delete_run_step: Sequence[RunStep] = delete_run_step

    # RunEntityInput mutations
    create_run_entity_input: RunEntityInput = create_run_entity_input
    update_run_entity_input: Sequence[RunEntityInput] = update_run_entity_input
    delete_run_entity_input: Sequence[RunEntityInput] = delete_run_entity_input

    # WorkflowVersion mutations
    create_workflow_version: WorkflowVersion = create_workflow_version
    update_workflow_version: Sequence[WorkflowVersion] = update_workflow_version
    delete_workflow_version: Sequence[WorkflowVersion] = delete_workflow_version
