"""
Supported GraphQL queries for files and entities

Auto-generated by running 'make codegen'. Do not edit.
Make changes to the template codegen/templates/api/queries.py.j2 instead.
"""

import strawberry
from strawberry import relay
from typing import Sequence, List
from api.types.workflow_run import (
    WorkflowRun,
    resolve_workflow_runs,
    WorkflowRunAggregate,
    resolve_workflow_runs_aggregate,
)
from api.types.workflow import Workflow, resolve_workflows, WorkflowAggregate, resolve_workflows_aggregate
from api.types.workflow_run_step import (
    WorkflowRunStep,
    resolve_workflow_run_steps,
    WorkflowRunStepAggregate,
    resolve_workflow_run_steps_aggregate,
)
from api.types.workflow_run_entity_input import (
    WorkflowRunEntityInput,
    resolve_workflow_run_entity_inputs,
    WorkflowRunEntityInputAggregate,
    resolve_workflow_run_entity_inputs_aggregate,
)
from api.types.workflow_version import (
    WorkflowVersion,
    resolve_workflow_versions,
    WorkflowVersionAggregate,
    resolve_workflow_versions_aggregate,
)


@strawberry.type
class Query:
    # Allow relay-style queries by node ID
    node: relay.Node = relay.node()
    nodes: List[relay.Node] = relay.node()

    # Query entities
    workflow_runs: Sequence[WorkflowRun] = resolve_workflow_runs
    workflows: Sequence[Workflow] = resolve_workflows
    workflow_run_steps: Sequence[WorkflowRunStep] = resolve_workflow_run_steps
    workflow_run_entity_inputs: Sequence[WorkflowRunEntityInput] = resolve_workflow_run_entity_inputs
    workflow_versions: Sequence[WorkflowVersion] = resolve_workflow_versions

    # Query entity aggregates
    workflow_runs_aggregate: WorkflowRunAggregate = resolve_workflow_runs_aggregate
    workflows_aggregate: WorkflowAggregate = resolve_workflows_aggregate
    workflow_run_steps_aggregate: WorkflowRunStepAggregate = resolve_workflow_run_steps_aggregate
    workflow_run_entity_inputs_aggregate: WorkflowRunEntityInputAggregate = resolve_workflow_run_entity_inputs_aggregate
    workflow_versions_aggregate: WorkflowVersionAggregate = resolve_workflow_versions_aggregate
