"""
Supported GraphQL queries for files and entities

Auto-generated by running 'make codegen'. Do not edit.
Make changes to the template codegen/templates/api/queries.py.j2 instead.
"""

import strawberry
from strawberry import relay
from typing import Sequence, List
from api.types.run import Run, resolve_runs
from api.types.workflow import Workflow, resolve_workflows
from api.types.run_step import RunStep, resolve_run_steps
from api.types.run_entity_input import RunEntityInput, resolve_run_entity_inputs
from api.types.workflow_version import WorkflowVersion, resolve_workflow_versions


@strawberry.type
class Query:
    # Allow relay-style queries by node ID
    node: relay.Node = relay.node()
    nodes: List[relay.Node] = relay.node()

    # Query entities
    runs: Sequence[Run] = resolve_runs
    workflows: Sequence[Workflow] = resolve_workflows
    run_steps: Sequence[RunStep] = resolve_run_steps
    run_entity_inputs: Sequence[RunEntityInput] = resolve_run_entity_inputs
    workflow_versions: Sequence[WorkflowVersion] = resolve_workflow_versions
