"""add contigs to the db

Create Date: 2023-09-12 21:53:04.487252

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "20230912_145303"
down_revision = "20230828_141240"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contig",
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.String(), nullable=False),
        sa.Column("sequencing_read_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["entity_id"], ["entity.id"], name=op.f("fk_contig_entity_id_entity")),
        sa.ForeignKeyConstraint(
            ["sequencing_read_id"],
            ["sequencing_read.entity_id"],
            name=op.f("fk_contig_sequencing_read_id_sequencing_read"),
        ),
        sa.PrimaryKeyConstraint("entity_id", name=op.f("pk_contig")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contig")
    # ### end Alembic commands ###
