version: '3.8'

x-aws-variables: &aws-variables
  ? AWS_ACCESS_KEY_ID
  ? AWS_SECRET_ACCESS_KEY
  ? AWS_SESSION_TOKEN
  ? AWS_REGION
  ? AWS_DEFAULT_REGION

x-db-variables: &db-variables
  ? PLATFORMICS_DATABASE_HOST=postgres.czidnet
  ? PLATFORMICS_DATABASE_PORT=5432
  ? PLATFORMICS_DATABASE_USER=postgres
  ? PLATFORMICS_DATABASE_PASSWORD=password_postgres
  ? PLATFORMICS_DATABASE_NAME=workflows

x-webservice-variables: &webservice-variables
  ? WORKERS=2

x-redis-variables: &redis-variables
  ? PLATFORMICS_EVENT_BUS__REDIS__REDIS_URL=redis://redis.czidnet:6378
  ? PLATFORMICS_EVENT_BUS__REDIS__QUEUE_NAME=workflow-events
  
x-workflow-variables: &workflow-variables
  ? ENVIRONMENT
  ? BOTO_ENDPOINT_URL=http://motoserver.czidnet:4000
  ? ENTITY_SERVICE_URL=http://entities.czidnet:8008
  ? DEFAULT_UPLOAD_BUCKET=local-bucket
  ? ENTITY_SERVICE_AUTH_TOKEN=eyJhbGciOiJFQ0RILUVTIiwiZW5jIjoiQTI1NkNCQy1IUzUxMiIsImVwayI6eyJjcnYiOiJQLTM4NCIsImt0eSI6IkVDIiwieCI6Ik5Nc3ZKbXVuYnBXY0VsdVlJTmRVeVVIcUkzbjZCR2VQd2V3ajRXS0pVdEt0QXhmUUtrVE81M2kzQ2dSZkZYVEQiLCJ5IjoiYmp6TkJuZjExWjRIV3dBVm95UVpSOGRWSERicW9wTjhvQkJZYnIxQlBiU1llZHdaWkVuYzJqS21rY0xxcloxTiJ9LCJraWQiOiItQmx2bF9wVk5LU2JRQ2N5dGV4UzNfMk5MaHBia2J6LVk5VFFjbkY5S1drIiwidHlwIjoiSldFIn0..Ymjmtj6nXp8r8AFe8AgI1g.e_39w7OXGJaOVKL_QkP38rvlcEeSgFQsxT0rTdCgI5E-b328zlVHagLSFZ_Iqvqiy6Z8KcU4pLJ3NTaW3Ys_YQsnUn6yUEvwqOY2KESB0mT0Bp3qpNYRBZJVA8PW43YAbOnO7h7ZTwQZJfwMzwhcaaYeZW8pN9rvcNtQX3rgBubSuR-LHKL6k4uAMPh9A8ZxXKZgpI6tpJPxE-uspvYi-foW8VyjZtwOUMvMp3lfZPyL1oQIv_rEUhOGNO_lfi339QcT6F7DwBjXK6C_7U65F-dFZScnReLnVczPfHhJ7z3NnVt46sFcddgZpLIpQyzA6puCcDoRm5ZZCVvm8h-LHVy-9dGWLVxBRhGRdBwBhbiVu2O_CNeVabXl8JhAs3oeV2zDgYfOj_-kkHWsbgHZ0y-tc-HtgoXzsUqaRP1IXQ3g3VDES7UjsaKsfxgURH5EIsrdWwFrWHGoLNfGwwPSwTBI5Mul7LT10-Pg_uBBCiHfQIDqerRQeADRFhV_07GYatBDt-RxwNL4bO59V8ewCzhpdCYRpL363HGldT1Pic-SpTk2NsY2t8MA6__FhJU9JSKYwJpeKMaGLUHA_40PEQ.gb5q-WZTU-ZKpV7WYFbMGMEF2CZIBrFlCUeaZ5ffPDU
  ? DEFAULT_UPLOAD_PROTOCOL=S3 # don't need this in workflows
  ? PLATFORMICS_WORKFLOW_RUNNER_PLUGIN=local
  ? PLATFORMICS_EVENT_BUS_PLUGIN=redis
  ? PLATFORMICS_EVENT_BUS__SWIPE__BOTO_ENDPOINT_URL=http://motoserver.czidnet:4000
  ? PLATFORMICS_EVENT_BUS__SWIPE__SQS_QUEUE_URL=http://motoserver.czidnet:4000/123456789012/swipe-test-notifications-sfn-notifications-queue

x-cerbos-variables: &cerbos-variables
  ? CERBOS_URL=http://wf-cerbos:3592
  ? JWK_PUBLIC_KEY_FILE=/workflows/test_infra/fixtures/public_key.pem
  ? JWK_PRIVATE_KEY_FILE=/workflows/test_infra/fixtures/private_key.pem

services:
  redis:
    image: redis:7
    ports:
      - "6378:6378"
    command: ["redis-server", "--port", "6378"]
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password_postgres
      - POSTGRES_DB=workflows
      # The postgres image declares a mounted volume at /var/lib/postgresql/data
      # by default, which means that the data in that directory is difficult to
      # snapshot and export. Here, we're telling Postgres to use this (non-mounted)
      # directory as its storage location instead so it works with our db snapshot
      # workflow.
      - PGDATA=/var/lib/platformics/data
  workflows:
    build:
      context: ".."
      dockerfile: "workflows/Dockerfile"
      args:
        - BUILDKIT_INLINE_CACHE=1
    image: "platformics-workflows"
    restart: always
    volumes:
      - .:/workflows
      # mount /tmp for local runner which uses miniwdl
      - /tmp:/tmp
      # enable docker in docker
      - /var/run/docker.sock:/var/run/docker.sock
      - ../platformics:/workflows/platformics
    ports:
      - 8042:8042
    stdin_open: true # Helps with pdb
    tty: true # Helps with pdb
    environment:
      <<: [*aws-variables, *db-variables, *redis-variables, *workflow-variables, *cerbos-variables, *webservice-variables]
  workflows-worker:
    build:
      context: ".."
      dockerfile: "workflows/Dockerfile"
      args:
        - BUILDKIT_INLINE_CACHE=1
    image: "platformics-workflows"
    command: ["python3", "api/loader/run_loader.py"]
    restart: always
    volumes:
      - .:/workflows
    stdin_open: true # Helps with pdb
    tty: true # Helps with pdb
    environment:
      <<: [*aws-variables, *db-variables, *redis-variables, *workflow-variables, *cerbos-variables]
  wf-cerbos:
    image: ghcr.io/cerbos/cerbos:0.29.0
    volumes:
      - ./cerbos:/workflows
    command:
      ["server", "--config", "/workflows/config/config.yaml"]
networks:
  default:
    name: czidnet
    driver: overlay
    attachable: true
    external: true
