version: '3.8'

x-aws-variables: &aws-variables
  ? AWS_ACCESS_KEY_ID=123
  ? AWS_SECRET_ACCESS_KEY=123
  ? AWS_SESSION_TOKEN=123
  ? AWS_REGION=us-east-1
  ? AWS_DEFAULT_REGION=us-east-1

x-db-variables: &db-variables
  ? PLATFORMICS_DATABASE_HOST=postgres.czidnet
  ? PLATFORMICS_DATABASE_PORT=5432
  ? PLATFORMICS_DATABASE_USER=postgres
  ? PLATFORMICS_DATABASE_PASSWORD=password_postgres
  ? PLATFORMICS_DATABASE_NAME=platformics

x-webservice-variables: &webservice-variables
  ? WORKERS=2

x-redis-variables: &redis-variables
  ? PLATFORMICS_EVENT_BUS__REDIS__REDIS_URL=redis://redis.czidnet:6378
  ? PLATFORMICS_EVENT_BUS__REDIS__QUEUE_NAME=workflow-events
  
x-workflow-variables: &workflow-variables
  ? ENVIRONMENT=test
  ? IDENTITY_SERVICE_BASE_URL=http://web.czidnet:3001
  ? BOTO_ENDPOINT_URL=http://motoserver.czidnet:4000
  ? ENTITY_SERVICE_URL=http://entities.czidnet:8008
  ? DEFAULT_UPLOAD_BUCKET=local-bucket
  ? DEFAULT_UPLOAD_PROTOCOL=S3 # don't need this in workflows
  ? PLATFORMICS_EVENT_BUS_PLUGIN=redis
  ? PLATFORMICS_EVENT_BUS__SWIPE__SQS_QUEUE_URL=http://motoserver.czidnet:4000/123456789012/swipe-test-notifications-sfn-notifications-queue
  ? PLATFORMICS_EVENT_BUS__SWIPE__SQS_ENDPOINT=http://motoserver.czidnet:4000
  ? PLATFORMICS_WORKFLOW_RUNNER_PLUGIN=local
  ? PLATFORMICS_WORKFLOW_RUNNER__LOCAL__S3_ENDPOINT=http://motoserver.czidnet:4000
  ? PLATFORMICS_WORKFLOW_RUNNER__SWIPE__OUTPUT_S3_PREFIX=s3://local-bucket/nextgen/
  ? PLATFORMICS_WORKFLOW_RUNNER__SWIPE__STATE_MACHINE_ARN=arn:aws:states:us-east-1:123456789012:stateMachine:swipe-test-default-wdl
  ? PLATFORMICS_WORKFLOW_RUNNER__SWIPE__SFN_ENDPOINT=http://stepfunctions.czidnet:8083
  ? SERVICE_NAME=workflows

x-cerbos-variables: &cerbos-variables
  ? CERBOS_URL=http://wf-cerbos:3592
  ? JWK_PUBLIC_KEY_FILE=/workflows/test_infra/fixtures/public_key.pem
  ? JWK_PRIVATE_KEY_FILE=/workflows/test_infra/fixtures/private_key.pem

services:
  redis:
    image: redis:7
    ports:
      - "6378:6378"
    command: ["redis-server", "--port", "6378"]
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password_postgres
      - POSTGRES_DB=platformicsworkflows
      # The postgres image declares a mounted volume at /var/lib/postgresql/data
      # by default, which means that the data in that directory is difficult to
      # snapshot and export. Here, we're telling Postgres to use this (non-mounted)
      # directory as its storage location instead so it works with our db snapshot
      # workflow.
      - PGDATA=/var/lib/platformics/data
  workflows:
    build:
      context: ".."
      dockerfile: "workflows/Dockerfile"
      args:
        - BUILDKIT_INLINE_CACHE=1
    image: "platformics-workflows"
    restart: always
    volumes:
      - .:/workflows
      # mount /tmp for local runner which uses miniwdl
      - /tmp:/tmp
      # enable docker in docker
      - /var/run/docker.sock:/var/run/docker.sock
      - ../platformics:/workflows/platformics
    ports:
      - 8042:8042
    stdin_open: true # Helps with pdb
    tty: true # Helps with pdb
    environment:
      <<: [*aws-variables, *db-variables, *redis-variables, *workflow-variables, *cerbos-variables, *webservice-variables]
  workflows-worker:
    build:
      context: ".."
      dockerfile: "workflows/Dockerfile"
      args:
        - BUILDKIT_INLINE_CACHE=1
    image: "platformics-workflows"
    command: ["python3", "api/loader/run_loader.py"]
    ports:
        - 8000:8000
    restart: always
    volumes:
      - .:/workflows
    stdin_open: true # Helps with pdb
    tty: true # Helps with pdb
    environment:
      <<: [*aws-variables, *db-variables, *redis-variables, *workflow-variables, *cerbos-variables]
  wf-cerbos:
    image: ghcr.io/cerbos/cerbos:0.29.0
    volumes:
      - ./cerbos:/var/policies/cerbos/
    command:
      ["server", "--config", "/var/policies/cerbos/config/config.yaml"]
networks:
  default:
    name: czidnet
    driver: overlay
    attachable: true
    external: true
