"""
Pydantic validator for Workflow

Auto-generated by running 'make codegen'. Do not edit.
Make changes to the template codegen/templates/api/types/class_name.py.j2 instead.
"""

# ruff: noqa: E501 Line too long


import datetime

from pydantic import BaseModel, ConfigDict, Field, StringConstraints
from typing_extensions import Annotated


class WorkflowCreateInputValidator(BaseModel):
    # Pydantic stuff
    model_config = ConfigDict(from_attributes=True)
    name: Annotated[
        str | None,
        StringConstraints(
            strip_whitespace=True,
        ),
    ]
    default_version: Annotated[
        str | None,
        StringConstraints(
            strip_whitespace=True,
        ),
    ]
    minimum_supported_version: Annotated[
        str | None,
        StringConstraints(
            strip_whitespace=True,
        ),
    ]
    collection_id: Annotated[
        int,
        Field(
            ge=0,
        ),
    ]
    deleted_at: Annotated[datetime.datetime | None, Field()]


class WorkflowUpdateInputValidator(BaseModel):
    # Pydantic stuff
    model_config = ConfigDict(from_attributes=True)
    name: Annotated[
        str | None,
        StringConstraints(
            strip_whitespace=True,
        ),
    ]
    default_version: Annotated[
        str | None,
        StringConstraints(
            strip_whitespace=True,
        ),
    ]
    minimum_supported_version: Annotated[
        str | None,
        StringConstraints(
            strip_whitespace=True,
        ),
    ]
    deleted_at: Annotated[datetime.datetime | None, Field()]
