"""
Pydantic validator for WorkflowRunStep

Auto-generated by running 'make codegen'. Do not edit.
Make changes to the template codegen/templates/api/types/class_name.py.j2 instead.
"""

# ruff: noqa: E501 Line too long




import typing
import datetime
import uuid

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import Annotated





class WorkflowRunStepCreateInputValidator(BaseModel):
    # Pydantic stuff
    model_config = ConfigDict(from_attributes=True)

    collection_id: Annotated[ int, Field()] 
    workflow_run_id: Annotated[ uuid.UUID | None, Field()]
    started_at: Annotated[ datetime.datetime | None, Field()]
    ended_at: Annotated[ datetime.datetime | None, Field()]
# TODO what do we do about enums here. GraphQL is supposed to take care of that for us I think?
#    status: Annotated[ WorkflowRunStepStatus | None, Field()] 
class WorkflowRunStepUpdateInputValidator(BaseModel):
    # Pydantic stuff
    model_config = ConfigDict(from_attributes=True)

    collection_id: Annotated[ int | None, Field()] 
    workflow_run_id: Annotated[ uuid.UUID | None, Field()]
    started_at: Annotated[ datetime.datetime | None, Field()]
    ended_at: Annotated[ datetime.datetime | None, Field()]
# TODO what do we do about enums here. GraphQL is supposed to take care of that for us I think?
#    status: Annotated[ WorkflowRunStepStatus | None, Field()] 