"""
Factory for generating IndexFile objects.

Auto-generated by running 'make codegen'. Do not edit.
Make changes to the template codegen/templates/test_infra/factories/class_name.py.j2 instead.
"""

# ruff: noqa: E501 Line too long

import factory
from database.models import IndexFile
from test_infra.factories.main import CommonFactory, FileFactory
from test_infra.factories.upstream_database import UpstreamDatabaseFactory
from test_infra.factories.host_organism import HostOrganismFactory
from factory import Faker, fuzzy
from faker_biology.bioseq import Bioseq
from faker_biology.physiology import Organ
from faker_enum import EnumProvider

Faker.add_provider(Bioseq)
Faker.add_provider(Organ)
Faker.add_provider(EnumProvider)


class IndexFileFactory(CommonFactory):
    class Meta:
        sqlalchemy_session = None  # workaround for a bug in factoryboy
        model = IndexFile
        # Match entity_id with existing db rows to determine whether we should
        # create a new row or not.
        sqlalchemy_get_or_create = ("entity_id",)

    name = fuzzy.FuzzyChoice(
        [
            "nt",
            "nt_loc",
            "nt_info",
            "nr",
            "nr_loc",
            "lineage",
            "accession2taxid",
            "deuterostome",
            "taxon_blacklist",
            "minimap2_long",
            "minimap2_short",
            "diamond",
            "star",
            "bowtie2",
            "bowtie2_v2",
            "minimap2_dna",
            "minimap2_rna",
            "hisat2",
            "kallisto",
            "original_transcripts_gtf",
        ]
    )
    version = fuzzy.FuzzyText()
    file = factory.RelatedFactory(
        FileFactory,
        factory_related_name="entity",
        entity_field_name="file",
        file_format="fastq",
    )
    upstream_database = factory.SubFactory(
        UpstreamDatabaseFactory,
        owner_user_id=factory.SelfAttribute("..owner_user_id"),
        collection_id=factory.SelfAttribute("..collection_id"),
    )
    host_organism = factory.SubFactory(
        HostOrganismFactory,
        owner_user_id=factory.SelfAttribute("..owner_user_id"),
        collection_id=factory.SelfAttribute("..collection_id"),
    )
