"""
Factory for generating MetricConsensusGenome objects.

Auto-generated by running 'make codegen'. Do not edit.
Make changes to the template codegen/templates/test_infra/factories/class_name.py.j2 instead.
"""

# ruff: noqa: E501 Line too long

import random
import factory
from database.models import MetricConsensusGenome
from test_infra.factories.main import CommonFactory, FileFactory
from test_infra.factories.consensus_genome import ConsensusGenomeFactory
from factory import Faker, fuzzy
from faker_biology.bioseq import Bioseq
from faker_biology.physiology import Organ
from faker_enum import EnumProvider

Faker.add_provider(Bioseq)
Faker.add_provider(Organ)
Faker.add_provider(EnumProvider)


class MetricConsensusGenomeFactory(CommonFactory):
    class Meta:
        sqlalchemy_session = None  # workaround for a bug in factoryboy
        model = MetricConsensusGenome
        # Match entity_id with existing db rows to determine whether we should
        # create a new row or not.
        sqlalchemy_get_or_create = ("entity_id",)

    consensus_genome = factory.SubFactory(
        ConsensusGenomeFactory,
        owner_user_id=factory.SelfAttribute("..owner_user_id"),
        collection_id=factory.SelfAttribute("..collection_id"),
    )
    reference_genome_length = fuzzy.FuzzyFloat(1, 100)
    percent_genome_called = fuzzy.FuzzyFloat(1, 100)
    percent_identity = fuzzy.FuzzyFloat(1, 100)
    gc_percent = fuzzy.FuzzyFloat(1, 100)
    total_reads = fuzzy.FuzzyInteger(1, 1000)
    mapped_reads = fuzzy.FuzzyInteger(1, 1000)
    ref_snps = fuzzy.FuzzyInteger(1, 1000)
    n_actg = fuzzy.FuzzyInteger(1, 1000)
    n_missing = fuzzy.FuzzyInteger(1, 1000)
    n_ambiguous = fuzzy.FuzzyInteger(1, 1000)
    coverage_depth = fuzzy.FuzzyFloat(1, 100)
    coverage_breadth = fuzzy.FuzzyFloat(1, 100)
    coverage_bin_size = fuzzy.FuzzyFloat(1, 100)
    coverage_total_length = fuzzy.FuzzyInteger(1, 1000)
    coverage_viz = factory.LazyAttribute(lambda o: [[random.randint(0, 10) for _ in range(5)]] * random.randint(2, 5))
