"""
Factory for generating Sample objects.

Auto-generated by running 'make codegen'. Do not edit.
Make changes to the template codegen/templates/test_infra/factories/class_name.py.j2 instead.
"""

# ruff: noqa: E501 Line too long

import factory
from database.models import Sample
from test_infra.factories.main import CommonFactory
from test_infra.factories.taxon import TaxonFactory
from factory import Faker, fuzzy
from faker_biology.bioseq import Bioseq
from faker_biology.physiology import Organ
from faker_enum import EnumProvider

Faker.add_provider(Bioseq)
Faker.add_provider(Organ)
Faker.add_provider(EnumProvider)


class SampleFactory(CommonFactory):
    class Meta:
        sqlalchemy_session = None  # workaround for a bug in factoryboy
        model = Sample
        # Match entity_id with existing db rows to determine whether we should
        # create a new row or not.
        sqlalchemy_get_or_create = ("entity_id",)

    name = fuzzy.FuzzyText()
    sample_type = factory.Faker("organ")
    water_control = factory.Faker("boolean")
    collection_date = factory.Faker("date")
    collection_location = factory.Faker("city")
    description = fuzzy.FuzzyText()
    host_taxon = factory.SubFactory(
        TaxonFactory,
        owner_user_id=factory.SelfAttribute("..owner_user_id"),
        collection_id=factory.SelfAttribute("..collection_id"),
    )
