# Auto-generated by running 'make codegen'. Do not edit.
# Make changes to the template codegen/templates/test_infra/factories/class_name.py.j2 instead.

# ruff: noqa: E501 Line too long

import factory
from database.models import Taxon
from test_infra.factories.main import CommonFactory
from test_infra.factories.upstream_database import UpstreamDatabaseFactory
from factory import Faker, fuzzy
from faker_biology.bioseq import Bioseq
from faker_biology.physiology import Organ
from faker_enum import EnumProvider

Faker.add_provider(Bioseq)
Faker.add_provider(Organ)
Faker.add_provider(EnumProvider)


class TaxonFactory(CommonFactory):
    class Meta:
        sqlalchemy_session = None  # workaround for a bug in factoryboy
        model = Taxon
        # Match entity_id with existing db rows to determine whether we should
        # create a new row or not.
        sqlalchemy_get_or_create = ("entity_id",)

    wikipedia_id = fuzzy.FuzzyText()
    description = fuzzy.FuzzyText()
    common_name = fuzzy.FuzzyText()
    name = fuzzy.FuzzyText()
    is_phage = factory.Faker("boolean")
    upstream_database = factory.SubFactory(
        UpstreamDatabaseFactory,
        owner_user_id=factory.SelfAttribute("..owner_user_id"),
        collection_id=factory.SelfAttribute("..collection_id"),
    )
    upstream_database_identifier = fuzzy.FuzzyText()
    level = fuzzy.FuzzyChoice(["species", "genus", "family"])
    tax_id = fuzzy.FuzzyInteger(1, 1000)
    tax_id_parent = fuzzy.FuzzyInteger(1, 1000)
    tax_id_species = fuzzy.FuzzyInteger(1, 1000)
    tax_id_genus = fuzzy.FuzzyInteger(1, 1000)
    tax_id_family = fuzzy.FuzzyInteger(1, 1000)
    tax_id_order = fuzzy.FuzzyInteger(1, 1000)
    tax_id_class = fuzzy.FuzzyInteger(1, 1000)
    tax_id_phylum = fuzzy.FuzzyInteger(1, 1000)
    tax_id_kingdom = fuzzy.FuzzyInteger(1, 1000)
