# Auto-generated by running 'make codegen'. Do not edit.
# Make changes to the template codegen/templates/test_infra/factories/class_name.py.j2 instead.

# ruff: noqa: E501 Line too long

from database.models import UpstreamDatabase
from test_infra.factories.main import CommonFactory
from factory import Faker, fuzzy
from faker_biology.bioseq import Bioseq
from faker_biology.physiology import Organ
from faker_enum import EnumProvider

Faker.add_provider(Bioseq)
Faker.add_provider(Organ)
Faker.add_provider(EnumProvider)


class UpstreamDatabaseFactory(CommonFactory):
    class Meta:
        sqlalchemy_session = None  # workaround for a bug in factoryboy
        model = UpstreamDatabase
        # Match required fields with existing db rows to determine whether we should
        # create a new row or not.
        sqlalchemy_get_or_create = ("name",)

    name = fuzzy.FuzzyText()
