"""
Factory for generating Run objects.

Auto-generated by running 'make codegen'. Do not edit.
Make changes to the template codegen/templates/test_infra/factories/class_name.py.j2 instead.
"""

# ruff: noqa: E501 Line too long

import factory
from database.models import Run
from test_infra.factories.main import CommonFactory, FileFactory
from test_infra.factories.workflow_version import WorkflowVersionFactory
from factory import Faker, fuzzy
from faker_biology.bioseq import Bioseq
from faker_biology.physiology import Organ
from faker_enum import EnumProvider

Faker.add_provider(Bioseq)
Faker.add_provider(Organ)
Faker.add_provider(EnumProvider)


class RunFactory(CommonFactory):
    class Meta:
        sqlalchemy_session = None  # workaround for a bug in factoryboy
        model = Run
        # Match entity_id with existing db rows to determine whether we should
        # create a new row or not.
        sqlalchemy_get_or_create = ("entity_id",)
    
    user_id = fuzzy.FuzzyInteger(1, 1000)
    project_id = fuzzy.FuzzyInteger(1, 1000)
    started_at = factory.Faker("date")
    ended_at = factory.Faker("date")
    execution_id = fuzzy.FuzzyText()
    outputs_json = fuzzy.FuzzyText()
    inputs_json = fuzzy.FuzzyText()
    status = fuzzy.FuzzyChoice([
        "SUCCEEDED", 
        "FAILED", 
        "PENDING", 
        "STARTED", 
        "RUNNING"
    ])
    workflow_version = factory.SubFactory(
        WorkflowVersionFactory,
        owner_user_id=factory.SelfAttribute("..owner_user_id"),
        collection_id=factory.SelfAttribute("..collection_id"),
    )
