"""
SQLAlchemy database model for ReferenceGenome

Auto-generated by running 'make codegen'. Do not edit.
Make changes to the template codegen/templates/database/models/class_name.py.j2 instead.
"""

import uuid
from typing import TYPE_CHECKING

from platformics.database.models.base import Entity
from sqlalchemy import ForeignKey, String
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

if TYPE_CHECKING:
    from database.models.file import File
    from database.models.consensus_genome import ConsensusGenome
else:
    File = "File"
    ConsensusGenome = "ConsensusGenome"


class ReferenceGenome(Entity):
    __tablename__ = "reference_genome"
    __mapper_args__ = {"polymorphic_identity": __tablename__, "polymorphic_load": "inline"}
    file_id: Mapped[uuid.UUID] = mapped_column(
        UUID,
        ForeignKey("file.id"),
        nullable=True,
        index=True,
    )
    file: Mapped["File"] = relationship(
        "File", foreign_keys=file_id, cascade="all, delete-orphan", single_parent=True, post_update=True
    )
    name: Mapped[str] = mapped_column(String, nullable=False)
    consensus_genomes: Mapped[list[ConsensusGenome]] = relationship(
        "ConsensusGenome",
        back_populates="reference_genome",
        uselist=True,
        foreign_keys="ConsensusGenome.reference_genome_id",
    )
    entity_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("entity.id"), nullable=False, primary_key=True)
