# Auto-generated by running 'make codegen'. Do not edit.
# Make changes to the template codegen/templates/api/queries.py.j2 instead.

import strawberry
from strawberry import relay
from typing import Sequence, List
from api.files import File, resolve_files
from api.types.sample import Sample, resolve_samples
from api.types.sequencing_read import SequencingRead, resolve_sequencing_reads
from api.types.contig import Contig, resolve_contigs


@strawberry.type
class Query:
    # Allow queries by node ID
    nodes: List[relay.Node] = relay.node()

    # Query files
    files: Sequence[File] = resolve_files

    # Query entities
    samples: Sequence[Sample] = resolve_samples
    sequencing_reads: Sequence[SequencingRead] = resolve_sequencing_reads
    contigs: Sequence[Contig] = resolve_contigs
