name: Deploy to Development
on:
  workflow_dispatch:
    inputs: 
      service: 
        type: choice
        description: Which service to deploy
        options:
        - workflows
        - entities

run-name: Deploy ${{ github.event.inputs.service }} to development for user ${{ github.actor }}
jobs:
  run-deploy-to-dev:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: dev
      service: ${{ github.event.inputs.service }}
      developer_name: ${{ github.actor }}
    secrets: inherit