name: Deploy to Sandbox
on:
  workflow_dispatch:
    inputs: 
      service: 
        type: choice
        description: Which service to deploy
        options:
        - workflows
        - entities

run-name: Deploy ${{ github.event.inputs.service }} to sandbox
jobs:
  run-deploy-to-sandbox:
    runs-on: [ARM64, self-hosted, Linux]
    uses: chanzuckerberg/czid-platformics/.github/workflows/reusable-deploy.yml
    environment: sandbox
    with:
      environment: sandbox
      service: ${{ github.event.inputs.service }}
    secrets: inherit