name: Deploy to Sandbox
on:
  workflow_dispatch:
    inputs: 
      service: 
        type: choice
        description: Which service to deploy
        options:
        - workflows
        - entities

run-name: Deploy ${{ github.event.inputs.service }} to sandbox
jobs:
  run-deploy-to-sandbox:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: sandbox
      service: ${{ github.event.inputs.service }}
      developer_name: ${{ github.actor }}
    secrets: inherit