name: Entities tests

on:
  push:
    branches:
      - main
    paths:
      - "entities/**"
  pull_request:
    branches: "**"
    paths:
      - "entities/**"

jobs:
  py-lint:
    runs-on: [ARM64, self-hosted, Linux]
    steps:
      - uses: actions/checkout@v3
      # Build images and run linters
      - name: Lint Python
        working-directory: entities
        run: |
          make gha-setup
          make local-build
          make check-lint
  py-test:
    runs-on: [ARM64, self-hosted, Linux]
    steps:
      - uses: actions/checkout@v3
      # Set up a local dev env and run tests
      - name: Set up deps
        run: |
          make gha-setup
      - name: Run tests
        working-directory: entities
        run: |
          make local-init
          make local-tests
