# This is so Cerbos complains if our principal object format doesn't meet the expected shape.
# Unfortunately, the "plan" code path we use doesn't seem to enforce this properly.
# The cerbos tests do, at least, so it's not entirely useless.
---
server:
  httpListenAddr: ":3592"
  grpcListenAddr: ":3593"

engine:
  defaultPolicyVersion: "default"

schemas:
  enforcement: reject

auxData:
  jwt:
    disableVerification: true

storage:
  driver: "disk"
  disk:
    directory: "/var/policies/cerbos/policies"
    watchForChanges: true